---
# TODO iptables rules
- name: hcloud firewall rules
  connection: local
  block:
    - name: Create a webservers firewall
      hetzner.hcloud.hcloud_firewall:
        api_token: "{{ hcloud_token }}"
        name: webservers
        rules:
          - direction: in
            port: 80
            protocol: tcp
            source_ips:
              - 0.0.0.0/0
              - ::/0
            description: allow http
          - direction: in
            port: 80
            protocol: udp
            source_ips:
              - 0.0.0.0/0
              - ::/0
            description: allow http
          - direction: in
            port: 443
            protocol: tcp
            source_ips:
              - 0.0.0.0/0
              - ::/0
            description: allow https
          - direction: in
            port: 443
            protocol: udp
            source_ips:
              - 0.0.0.0/0
              - ::/0
            description: allow https
          - direction: out
            port: 80
            protocol: tcp
            destination_ips:
              - 0.0.0.0/0
              - ::/0
            description: allow http
          - direction: out
            port: 80
            protocol: udp
            destination_ips:
              - 0.0.0.0/0
              - ::/0
            description: allow http
          - direction: out
            port: 443
            protocol: tcp
            destination_ips:
              - 0.0.0.0/0
              - ::/0
            description: allow https
          - direction: out
            port: 443
            protocol: udp
            destination_ips:
              - 0.0.0.0/0
              - ::/0
            description: allow https
        state: present
    - name: Add the webservers firewall to hosts firewall list
      set_fact:
        hcloud_firewalls: "{{ hcloud_firewalls + [ 'webservers' ] }}"
